/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.actividad5_1;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

/**
 *
 * @author Salome Castilla
 */
public class ContactApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactApp.class.getName());

    /**
     * Creates new form ContactApp
     */
    public ContactApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Número = new javax.swing.JTextField();
        CREATE = new javax.swing.JButton();
        READ = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Número:");

        Número.addActionListener(this::NúmeroActionPerformed);

        CREATE.setBackground(new java.awt.Color(51, 204, 0));
        CREATE.setText("CREATE");
        CREATE.addActionListener(this::CREATEActionPerformed);

        READ.setBackground(new java.awt.Color(0, 51, 204));
        READ.setText("READ");
        READ.addActionListener(this::READActionPerformed);

        UPDATE.setBackground(new java.awt.Color(255, 255, 102));
        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(this::UPDATEActionPerformed);

        DELETE.setBackground(new java.awt.Color(204, 0, 0));
        DELETE.setText("DELETE");
        DELETE.addActionListener(this::DELETEActionPerformed);

        Clear.setText("Clear");
        Clear.addActionListener(this::ClearActionPerformed);

        Exit.setText("Exit");
        Exit.addActionListener(this::ExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Número, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Clear)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CREATE)
                                .addGap(26, 26, 26)
                                .addComponent(READ)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(UPDATE)
                                .addGap(52, 52, 52)
                                .addComponent(DELETE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(Exit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Número, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATE)
                    .addComponent(READ)
                    .addComponent(UPDATE)
                    .addComponent(DELETE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(Exit))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NúmeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NúmeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NúmeroActionPerformed

    private void CREATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEActionPerformed
        String newName = Nombre.getText().trim();
    String numeroStr = Número.getText().trim();

    if (newName.isEmpty() || numeroStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes ingresar nombre y número.");
        return;
    }

    try {
        long newNumber = Long.parseLong(numeroStr);
        File file = new File("friendsContact.txt");
        if (!file.exists()) file.createNewFile();

        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;

        while (raf.getFilePointer() < raf.length()) {
            String linea = raf.readLine();
            if (linea == null) break;
            String[] partes = linea.split("!");
            if (partes[0].equals(newName) || Long.parseLong(partes[1]) == newNumber) {
                found = true;
                break;
            }
        }

        if (!found) {
            raf.writeBytes(newName + "!" + newNumber);
            raf.writeBytes(System.lineSeparator());
            JOptionPane.showMessageDialog(this, "Contacto agregado: " + newName);
        } else {
            JOptionPane.showMessageDialog(this, "El contacto ya existe.");
        }
        raf.close();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El número solo debe contener dígitos.");
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_CREATEActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        String nombre = Nombre.getText().trim();
    String nuevoNumeroStr = Número.getText().trim();

    if (nombre.isEmpty() || nuevoNumeroStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa el nombre existente y el nuevo número.");
        return;
    }

    try {
        long nuevoNumero = Long.parseLong(nuevoNumeroStr);
        File file = new File("friendsContact.txt");
        File tmpFile = new File("temp.txt");
        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        RandomAccessFile tmpRaf = new RandomAccessFile(tmpFile, "rw");
        boolean found = false;

        while (raf.getFilePointer() < raf.length()) {
            String linea = raf.readLine();
            if (linea == null) break;
            String[] partes = linea.split("!");
            if (partes[0].equals(nombre)) {
                tmpRaf.writeBytes(nombre + "!" + nuevoNumero);
                found = true;
            } else {
                tmpRaf.writeBytes(linea);
            }
            tmpRaf.writeBytes(System.lineSeparator());
        }

        raf.seek(0); tmpRaf.seek(0);
        while (tmpRaf.getFilePointer() < tmpRaf.length()) {
            raf.writeBytes(tmpRaf.readLine());
            raf.writeBytes(System.lineSeparator());
        }
        raf.setLength(tmpRaf.length());
        tmpRaf.close(); raf.close();
        tmpFile.delete();

        JOptionPane.showMessageDialog(this, found
            ? "Contacto actualizado: " + nombre + " → " + nuevoNumero
            : "No se encontró el contacto: " + nombre);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El número solo debe contener dígitos.");
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void READActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_READActionPerformed
         try {
        File file = new File("friendsContact.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "No hay contactos guardados.");
            return;
        }

        RandomAccessFile raf = new RandomAccessFile(file, "r");
        StringBuilder sb = new StringBuilder("Contactos guardados:\n\n");
        int i = 1;

        while (raf.getFilePointer() < raf.length()) {
            String linea = raf.readLine();
            if (linea == null) break;
            String[] partes = linea.split("!");
            sb.append(i++).append(". ").append(partes[0])
              .append("  →  ").append(partes[1]).append("\n");
        }

        raf.close();
        JOptionPane.showMessageDialog(this, sb.toString());

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_READActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
         String nombre = Nombre.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa el nombre del contacto a eliminar.");
        return;
    }

    try {
        File file = new File("friendsContact.txt");
        File tmpFile = new File("temp.txt");
        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        RandomAccessFile tmpRaf = new RandomAccessFile(tmpFile, "rw");
        boolean found = false;

        while (raf.getFilePointer() < raf.length()) {
            String linea = raf.readLine();
            if (linea == null) break;
            String[] partes = linea.split("!");
            if (partes[0].equals(nombre)) {
                found = true;
                continue;
            }
            tmpRaf.writeBytes(linea);
            tmpRaf.writeBytes(System.lineSeparator());
        }

        raf.seek(0); tmpRaf.seek(0);
        while (tmpRaf.getFilePointer() < tmpRaf.length()) {
            raf.writeBytes(tmpRaf.readLine());
            raf.writeBytes(System.lineSeparator());
        }
        raf.setLength(tmpRaf.length());
        tmpRaf.close(); raf.close();
        tmpFile.delete();

        JOptionPane.showMessageDialog(this, found
            ? "Contacto eliminado: " + nombre
            : "No se encontró el contacto: " + nombre);

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_DELETEActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
            Nombre.setText("");
    Número.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Exit.setText("Exit");
        Exit.addActionListener(e -> System.exit(0));
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATE;
    private javax.swing.JButton Clear;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Número;
    private javax.swing.JButton READ;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
