/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio418;

/**
 *
 * @author Salome Castilla
 */
public class principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal.class.getName());

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Nombreequipo = new javax.swing.JTextField();
        Universidad = new javax.swing.JTextField();
        LenguajedeProgramacion = new javax.swing.JTextField();
        NombreIntegrante2 = new javax.swing.JTextField();
        NombreIntegrante1 = new javax.swing.JTextField();
        NombreIntegrante3 = new javax.swing.JTextField();
        NombreIntegrante4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ApellidoIntegrante1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ApellidoIntegrante2 = new javax.swing.JTextField();
        ApellidoIntegrante3 = new javax.swing.JTextField();
        ApellidoIntegrante4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del equipo");

        jLabel2.setText("Universidad");

        jLabel3.setText("Lenguaje de programacion");

        jLabel4.setText("Datos de los Integrantes");

        jLabel5.setText("Nombre Integrante");

        jLabel6.setText("Nombre Integrante");

        jLabel7.setText("Nombre Integrante");

        jLabel8.setText("Nombre Integrante");

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(this::IngresarActionPerformed);

        Borrar.setText("Borrar");
        Borrar.addActionListener(this::BorrarActionPerformed);

        NombreIntegrante2.addActionListener(this::NombreIntegrante2ActionPerformed);

        NombreIntegrante1.addActionListener(this::NombreIntegrante1ActionPerformed);

        NombreIntegrante3.addActionListener(this::NombreIntegrante3ActionPerformed);

        NombreIntegrante4.addActionListener(this::NombreIntegrante4ActionPerformed);

        jLabel9.setText("Apellido Integrante");

        ApellidoIntegrante1.addActionListener(this::ApellidoIntegrante1ActionPerformed);

        jLabel10.setText("Apellido Integrante");

        jLabel11.setText("Apellido Integrante");

        jLabel12.setText("Apellido Integrante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LenguajedeProgramacion, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(Universidad)
                            .addComponent(Nombreequipo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Ingresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreIntegrante2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreIntegrante1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreIntegrante4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreIntegrante3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ApellidoIntegrante1)
                                    .addComponent(ApellidoIntegrante2)
                                    .addComponent(ApellidoIntegrante3)
                                    .addComponent(ApellidoIntegrante4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Borrar)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombreequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Universidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LenguajedeProgramacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NombreIntegrante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ApellidoIntegrante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NombreIntegrante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ApellidoIntegrante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(NombreIntegrante3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ApellidoIntegrante3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(NombreIntegrante4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(ApellidoIntegrante4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Borrar)
                            .addComponent(Ingresar))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreIntegrante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreIntegrante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreIntegrante2ActionPerformed

    private void NombreIntegrante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreIntegrante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreIntegrante1ActionPerformed

    private void NombreIntegrante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreIntegrante3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreIntegrante3ActionPerformed

    private void NombreIntegrante4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreIntegrante4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreIntegrante4ActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        try {
        // 1. Recolectar datos principales
        String nomEquipo = Nombreequipo.getText().trim();
        String univ = Universidad.getText().trim();
        String lenguaje = LenguajedeProgramacion.getText().trim();

        // Validar campos principales
        EquipoMaraton.validarCampo(nomEquipo);
        EquipoMaraton.validarCampo(univ);

        // 2. Instanciar el objeto de tu clase EquipoMaraton
        EquipoMaraton equipo = new EquipoMaraton(nomEquipo, univ, lenguaje);

        // Arreglos para recorrer los componentes en un ciclo
        javax.swing.JTextField[] camposNombres = {NombreIntegrante1, NombreIntegrante2, NombreIntegrante3, NombreIntegrante4};
        javax.swing.JTextField[] camposApellidos = {ApellidoIntegrante1, ApellidoIntegrante2, ApellidoIntegrante3, ApellidoIntegrante4};

        // 3. Recorrer integrantes y agregarlos
        for (int i = 0; i < 4; i++) {
            String nom = camposNombres[i].getText().trim();
            String ape = camposApellidos[i].getText().trim();

            if (!nom.isEmpty() && !ape.isEmpty()) {
                EquipoMaraton.validarCampo(nom);
                EquipoMaraton.validarCampo(ape);
                
                programador p = new programador(nom, ape);
                equipo.añadir(p);
            }
        }

        // 4. VERIFICACIÓN: Ventana emergente que demuestra que los datos se guardaron
        String reporte = "¡Equipo registrado con éxito!\n\n" +
                         "• Equipo: " + equipo.nombreEquipo + "\n" +
                         "• Universidad: " + equipo.universidad + "\n" +
                         "• Lenguaje: " + equipo.lenguajeProgramacion + "\n" +
                         "• Total Integrantes: " + equipo.tamañoEquipo + "/4";
        
        javax.swing.JOptionPane.showMessageDialog(this, reporte, "Verificación de Datos", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        // Si hay error (números en el nombre, texto muy largo, etc.) salta esto:
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error al ingresar datos", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_IngresarActionPerformed

    private void ApellidoIntegrante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoIntegrante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoIntegrante1ActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        Nombreequipo.setText("");
        Universidad.setText("");
        LenguajedeProgramacion.setText("");
        NombreIntegrante1.setText("");
ApellidoIntegrante1.setText("");
NombreIntegrante2.setText("");
ApellidoIntegrante2.setText("");
NombreIntegrante3.setText("");
ApellidoIntegrante3.setText("");
NombreIntegrante4.setText("");
ApellidoIntegrante4.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoIntegrante1;
    private javax.swing.JTextField ApellidoIntegrante2;
    private javax.swing.JTextField ApellidoIntegrante3;
    private javax.swing.JTextField ApellidoIntegrante4;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Ingresar;
    private javax.swing.JTextField LenguajedeProgramacion;
    private javax.swing.JTextField NombreIntegrante1;
    private javax.swing.JTextField NombreIntegrante2;
    private javax.swing.JTextField NombreIntegrante3;
    private javax.swing.JTextField NombreIntegrante4;
    private javax.swing.JTextField Nombreequipo;
    private javax.swing.JTextField Universidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
